//! Golden fixture tests for the Kraken `book` parser and its checksum.
//!
//! `checksum.json` fixtures carry CRC32 values computed independently in
//! Python (`zlib.crc32`, the reference implementation for this exact
//! algorithm) over the digit strings Kraken's own spec describes — not values
//! generated by this crate's own `checksum()` function. A test that only
//! checks a function against its own output proves nothing; these fixtures
//! are the actual cross-check.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use ma_core::{
    Book, BookState, Clock, DesyncReason, Integrity, Side, StreamId, Symbol, SystemClock, VenueId,
};
use ma_venues::KrakenSync;
use ma_venues::sync::{Outcome, RawFrame};

macro_rules! fixture {
    ($name:literal) => {
        include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/fixtures/kraken/",
            $name
        ))
    };
}

fn book() -> ma_venues::sync::VenueBook {
    ma_venues::sync::VenueBook::new(Box::new(KrakenSync::new("BTC/USD")), Symbol::new("BTC-USD"))
}

fn frame(json: &str) -> RawFrame {
    RawFrame::new(
        StreamId::new(VenueId::Kraken, Symbol::new("BTC-USD")),
        json.as_bytes().to_vec(),
        SystemClock.now(),
    )
}

fn levels(book: &Book, side: Side) -> Vec<(String, String)> {
    book.top_levels(side, 100)
        .iter()
        .map(|l| (l.price.to_string(), l.qty.to_string()))
        .collect()
}

#[test]
fn snapshot_with_a_matching_checksum_is_verified() {
    // 1205813205 was computed in Python against the exact digit strings in
    // this fixture's book (2 asks ascending, 2 bids descending, decimal
    // point removed, leading zeros stripped) — see the module doc.
    let mut vb = book();
    vb.feed(&frame(fixture!("snapshot.json"))).unwrap();

    assert_eq!(vb.book().state().integrity(), Some(Integrity::Verified));
    match vb.book().state() {
        BookState::Live {
            last_verified: Some(_),
            ..
        } => {}
        other => panic!("expected a verified Live book, got {other:?}"),
    }
    assert_eq!(
        levels(vb.book(), Side::Bid),
        [
            ("60000.00".to_owned(), "1.20000000".to_owned()),
            ("59950.00".to_owned(), "0.50000000".to_owned())
        ]
    );
}

#[test]
fn update_with_a_matching_checksum_stays_verified() {
    let mut vb = book();
    vb.feed(&frame(fixture!("snapshot.json"))).unwrap();
    vb.feed(&frame(fixture!("update.json"))).unwrap();

    match vb.book().state() {
        BookState::Live {
            integrity: Integrity::Verified,
            last_verified: Some(_),
            ..
        } => {}
        other => panic!("expected a verified Live book after the update, got {other:?}"),
    }
    assert_eq!(
        levels(vb.book(), Side::Ask),
        [("60020.00".to_owned(), "2.00000000".to_owned())],
        "ask 60010.00 carried qty 0.0 and should have been deleted"
    );
}

#[test]
fn a_wrong_checksum_desyncs_the_book_even_though_sequencing_is_fine() {
    // Kraken has no sequence numbers at all, so this is the *only* way a
    // Kraken book can be caught being wrong -- there is no gap to detect.
    let mut vb = book();
    vb.feed(&frame(fixture!("snapshot.json"))).unwrap();
    vb.feed(&frame(fixture!("update_bad_checksum.json")))
        .unwrap();

    match vb.book().state() {
        BookState::Desynced {
            reason: DesyncReason::ChecksumMismatch { expected, computed },
            ..
        } => {
            assert_eq!(expected, 1);
            assert_eq!(
                computed, 994_251_236,
                "our own checksum function disagrees with the Python reference"
            );
        }
        other => panic!("expected a ChecksumMismatch desync, got {other:?}"),
    }
}

#[test]
fn heartbeat_forwards_without_touching_book_trust() {
    let mut vb = book();
    vb.feed(&frame(fixture!("snapshot.json"))).unwrap();
    let outcomes = vb.feed(&frame(fixture!("heartbeat.json"))).unwrap();

    assert!(vb.book().state().is_live());
    assert!(outcomes
        .iter()
        .any(|o| matches!(o, ma_venues::Outcome::Event(ev) if matches!(ev.kind, ma_core::EventKind::Heartbeat { .. }))));
}

#[test]
fn a_subscribe_ack_with_no_channel_field_is_ignored() {
    let mut vb = book();
    let outcomes = vb.feed(&frame(fixture!("subscribe_ack.json"))).unwrap();

    assert!(outcomes.is_empty());
    assert_eq!(vb.book().state(), BookState::Uninitialized);
}

#[test]
fn exact_decimal_parsing_preserves_trailing_zeros_from_a_bare_json_number() {
    // The regression case for the f64 hazard this parser exists to avoid.
    // Kraken sends 0.00100000 as a bare JSON number (not a string). Naive
    // f64 deserialization prints it back as "0.001" (Rust's shortest
    // round-trip float formatting drops the trailing zeros), which after
    // point-removal and leading-zero-stripping becomes the checksum digit
    // "1" instead of the "100000" Kraken actually hashed -- silently
    // corrupting every checksum on a value like this.
    let mut vb = book();
    vb.feed(&frame(fixture!("exact_qty.json"))).unwrap();

    assert_eq!(
        levels(vb.book(), Side::Bid),
        [("60000.00".to_owned(), "0.00100000".to_owned())],
        "trailing zeros were lost somewhere between the wire and the book"
    );
}

#[test]
fn the_venue_clock_is_reported_on_updates_and_absent_from_snapshots() {
    // Kraken puts its timestamp inside each `data` entry, and only on
    // `update` messages. A field that appears on some messages and not others
    // could not order anything even if we were willing to trust it -- which
    // `docs/DESIGN.md` §7 says we are not.
    let mut vb = book();
    let snapshot = vb.feed(&frame(fixture!("snapshot.json"))).unwrap();
    assert!(
        venue_ts_of(&snapshot).is_none(),
        "kraken snapshots carry no timestamp; one appeared from somewhere"
    );

    let update = vb.feed(&frame(fixture!("update.json"))).unwrap();
    let venue_ts = venue_ts_of(&update).expect("kraken stamps updates");
    let nanos = venue_ts
        .duration_since(std::time::UNIX_EPOCH)
        .expect("post-epoch")
        .as_nanos();
    assert_eq!(nanos, 1_786_190_401_000_000_000, "2026-08-08T12:00:01Z");
}

/// The venue timestamp on the first content-bearing event of a batch.
fn venue_ts_of(outcomes: &[Outcome]) -> Option<std::time::SystemTime> {
    outcomes.iter().find_map(|o| match o {
        Outcome::Event(e) => e.venue_ts,
        Outcome::StateChanged { .. } => None,
    })
}
